name: Build Windows Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build package
        run: |
          powershell -NoProfile -ExecutionPolicy Bypass -File packaging/build_windows.ps1 -Python python

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PersonalAssistant-${{ github.ref_name }}
          path: |
            dist/PersonalAssistant.exe
            dist/PersonalAssistant-package.zip
